name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        buildpath: [""]
        buildconf: [""]
        artifactpath: [""]
        artifactname: [""]
        include:
          - buildpath: projects/Core/Haru.ModApi/Haru.ModApi.csproj
            buildconf: Debug
            artifactpath: projects/Core/Haru.ModApi/bin/Debug/net472
            artifactname: haru-modapi
          - buildpath: projects/Core/Haru.Loader/Haru.Loader.csproj
            buildconf: "Debug (BepInEx)"
            artifactpath: projects/Core/Haru.Loader/bin/Debug (BepInEx)/net472
            artifactname: haru-bepinex
          - buildpath: projects/Core/Haru.Loader/Haru.Loader.csproj
            buildconf: "Debug (Melon)"
            artifactpath: projects/Core/Haru.Loader/bin/Debug (Melon)/net472
            artifactname: haru-melon
          - buildpath: projects/Core/Haru.Loader/Haru.Loader.csproj
            buildconf: "Debug (NLog)"
            artifactpath: projects/Core/Haru.Loader/bin/Debug (NLog)/net472
            artifactname: haru-nlog
          - buildpath: projects/Mods/Senko.EftData/Senko.EftData.csproj
            buildconf: Debug
            artifactpath: projects/Mods/Senko.EftData/bin/Debug/net472
            artifactname: senko-eftdata
          - buildpath: projects/Mods/Senko.Langpack/Senko.Langpack.csproj
            buildconf: Debug
            artifactpath: projects/Mods/Senko.Langpack/bin/Debug/net472
            artifactname: senko-langpack

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --nologo --force --configuration ${{ matrix.buildconf }} ${{ matrix.buildpath }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifactname }}
        path: |
          ${{ matrix.artifactpath }}
          !projects/**/*.pdb