name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        artifactname: [ "" ]
        artifactpath: [ "" ]
        include:
          - artifactname: Haru.Server
            artifactpath: ./projects/Core/Haru.Server/bin/Debug/net472
          - artifactname: Haru.Client
            artifactpath: ./projects/Core/Haru.Client/bin/Debug/net472
        exclude:
          - artifactname: ""
            artifactpath: ""

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore projects
      run: dotnet restore --configfile ./projects/Nuget.config ./projects/Haru.sln

    - name: Build projects
      run: dotnet build --nologo --no-restore ./projects/Haru.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifactname }}
        path: |
          ${{ matrix.artifactpath }}
          !projects/**/*.pdb
          !projects/**/Assembly-CSharp.dll
          !projects/**/bsg.componentace.compression.libs.zlib.dll
          !projects/**/bsg.microsoft.extensions.objectpool.dll
          !projects/**/Newtonsoft.Json.dll
          !projects/**/System.Buffers.dll
          !projects/**/UnityEngine.dll
          !projects/**/UnityEngine.CoreModule.dll
          !projects/**/UnityEngine.UnityWebRequestModule.dll
          !projects/**/websocket-sharp.dll