name: .NET

on:
  push:
    branches: [ "main", "0.13.0" ]
  pull_request:
    branches: [ "main", "0.13.0" ]

jobs:
  build:
    strategy:
      matrix:
        artifactname: [ "" ]
        artifactpath: [ "" ]
        include:
          - artifactname: haru
            artifactpath: ./projects/Core/Haru/bin/Debug/net472
          - artifactname: haru-modapi
            artifactpath: ./projects/Core/Haru.ModApi/bin/Debug/net472
          - artifactname: haru-server
            artifactpath: ./projects/Core/Haru.Server/bin/Debug/net472
          - artifactname: haru-client
            artifactpath: ./projects/Core/Haru.Client/bin/Debug/net472
          - artifactname: senko-eftdata
            artifactpath: ./projects/Mods/Senko.EftData/bin/Debug/net472
          - artifactname: senko-langpack
            artifactpath: ./projects/Mods/Senko.Langpack/bin/Debug/net472
        exclude:
          - artifactname: ""
            artifactpath: ""

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore projects
      run: dotnet restore --configfile ./projects/Nuget.config ./projects/Haru.sln

    - name: Build projects
      run: dotnet build --nologo --no-restore ./projects/Haru.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifactname }}
        path: |
          ${{ matrix.artifactpath }}
          !projects/**/*.pdb